<?php
 //仅供学习交流   请勿删除 1329807895    采集地址为 http://api.pm8888.cn/api.php?type=
//官方彩
		$apiurls = [
			'actkeno'  => '/api.open.kj.code.actkeno',
			'bjkeno'   => 'http://f.apiplus.net/bjkl8.json',
			'jndkeno'  => '/api.open.kj.code.jndkeno',
			'hgkeno'   => '/api.open.kj.code.hgkeno',
			'twkeno'   => '/api.open.kj.code.twkeno',
			'cqssc'    => 'http://f.apiplus.net/cqssc.json',
			'xjssc'    => 'http://f.apiplus.net/xjssc.json',
			'tjssc'    => 'http://f.apiplus.net/tjssc.json',
			'dfssc'    => '/api.open.kj.code.dfssc',
			'df11x5'    => '/api.open.kj.code.df11x5',
			//--------------------------K3---------------------------------
			'nmgk3'    => 'http://api.pm8888.cn/api.php?type=nmgk3',
			'hebk3'    => 'http://f.apiplus.net/hebk3.json',
			'bjk3'     => 'http://f.apiplus.net/bjk3.json',
			'shk3'     => 'http://f.apiplus.net/shk3.json',
			'jlk3'     => 'http://f.apiplus.net/jlk3.json',
			'ahk3'     => 'http://f.apiplus.net/ahk3.json',
			'gxk3'     => 'http://f.apiplus.net/gxk3.json',
			'gsk3'     => 'http://www.apilottery.com/free/gsk3',
			'hubk3'    => 'http://f.apiplus.net/hubk3.json',
			'jxk3'     => 'http://f.apiplus.net/jxk3.json',
			'fjk3'		=> 'http://www.apilottery.com/free/fjk3',
			'nmgk3'		=> 'http://api.pm8888.cn/api.php?type=nmgk3',
			'gzk3'		=> 'http://api.pm8888.cn/api.php?type=gzk3',
			'jsk3'		=> 'http://f.apiplus.net/jsk3.json',
			'qhk3'		=> 'http://api.pm8888.cn/api.php?type=qhk3',
			'henk3'		=> 'http://api.pm8888.cn/api.php?type=henk3',
			//-----------------------------11X5---------------------
			'gd11x5'    => 'http://f.apiplus.net/gd11x5.json',
			'jx11x5'    => 'http://f.apiplus.net/jx11x5.json',
			'sh11x5'    => 'http://f.apiplus.net/sh11x5.json',
			'tj11x5'	=> 'http://api.pm8888.cn/api.php?type=tj11x5',
			'zj11x5'	=> 'http://api.pm8888.cn/api.php?type=zj11x5',
			'bj11x5'	=> 'http://f.apiplus.net/bj11x5.json',
			'yn11x5'	=> 'http://api.pm8888.cn/api.php?type=yn11x5',
			'nmg11x5'	=> 'http://api.pm8888.cn/api.php?type=nmg11x5',
			'gx11x5'	=> 'http://api.pm8888.cn/api.php?type=gx11x5',
			'qh11x5'	=> 'http://api.pm8888.cn/api.php?type=qh11x5',
			'shx11x5'	=> 'http://api.pm8888.cn/api.php?type=shx11x5',
			'hen11x5'	=> 'http://api.pm8888.cn/api.php?type=hen11x5',
			'gs11x5'	=> 'http://api.pm8888.cn/api.php?type=gs11x5',
			'heb11x5'	=> 'http://api.pm8888.cn/api.php?type=heb11x5',
			'hlj11x5'	=> 'http://api.pm8888.cn/api.php?type=hlj11x5',
			'sd11x5'	=> 'http://api.pm8888.cn/api.php?type=sd11x5',
			'xj11x5'	=> 'http://api.pm8888.cn/api.php?type=xj11x5',
			'js11x5'	=> 'http://api.pm8888.cn/api.php?type=js11x5',
			'fj11x5'	=> 'http://api.pm8888.cn/api.php?type=fj11x5',
			'ah11x5'	=> 'http://api.pm8888.cn/api.php?type=ah11x5',
			'hub11x5'	=> 'http://api.pm8888.cn/api.php?type=hub11x5',
			'jl11x5'	=> 'http://api.pm8888.cn/api.php?type=jl11x5',
			'sx11x5'	=> 'http://api.pm8888.cn/api.php?type=sx11x5',
			'ln11x5'	=> 'http://api.pm8888.cn/api.php?type=ln11x5',
			//-----------------------------X5  END-----------------------
			'gdkl10f'    => '/api.open.kj.code.gdkl10f',
			'tjkl10f'    => '/api.open.kj.code.tjkl10f',
			'cqkl10f'    => '/api.open.kj.code.cqkl10f',
			'bjpk10'     => 'http://f.apiplus.net/bjpk10.json',
			'txssc'     => 'http://api.pm8888.cn/api.php?type=txffc',
			'lhc'     => 'http://api.pm8888.cn/api.php?type=lhc',
			'fc3d'      => 'http://f.apiplus.net/fc3d.json',
			'pl3'       => 'http://f.apiplus.net/pl3.json',
			'xyft'       => 'http://api.pm8888.cn/api.php?type=xyft',
			'ynwfc'    => '/api.open.kj.code.ynwfc',
			'ynffc'    => '/api.open.kj.code.ynffc',
			'hnwfc'    => '/api.open.kj.code.hnwfc',
			'hnffc'    => '/api.open.kj.code.hnffc',

		];
